# -*- coding: utf-8 -*-
"""Data_visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OlBqYFrpz_ZV7g10hIoev5fcCFCb2ZL2

Line Plot
"""

import numpy as np
import matplotlib.pyplot as plt

x=np.array([9,13,15,24,31,46,53,66,68,81])
y=np.array([10,20,33,38,56,67,78,84,88,95])
z=np.array([67,61,56,53,58,41,32,31,22,17])
p=np.array([45,66,43,26,78,53,12,34,22,67])

plt.title('My first plot')
plt.grid()
plt.xlabel('First value')
plt.ylabel('Second value')
plt.xlim(0,90)
plt.ylim(0,90)
plt.xticks(range(0,101,10))
plt.yticks(range(0,101,10))
plt.plot(x,y)

plt.title('My first plot')
plt.grid()
plt.xlabel('First value')
plt.ylabel('Second value')
plt.xlim(0,90)
plt.ylim(0,90)
plt.xticks(range(0,101,10))
plt.yticks(range(0,101,10))
plt.plot(x,z)

plt.title('My first plot')
plt.grid()
plt.xlabel('First value')
plt.ylabel('Second value')
plt.xlim(0,90)
plt.ylim(0,90)
plt.xticks(range(0,101,10))
plt.yticks(range(0,101,10))
plt.plot(x,p)

plt.title('My first plot')
plt.grid()
plt.xlabel('First value')
plt.ylabel('Second value')
plt.xlim(0,90)
plt.ylim(0,90)
plt.xticks(range(0,101,10))
plt.yticks(range(0,101,10))
plt.plot(x,y, color='red', marker='o')

plt.title('My first plot')
plt.grid()
plt.xlabel('First value')
plt.ylabel('Second value')
plt.xlim(0,90)
plt.ylim(0,90)
plt.xticks(range(0,101,10))
plt.yticks(range(0,101,10))
plt.plot(x,y, color='#00FFFF', marker='o')

plt.title('My first plot')
plt.grid()
plt.xlabel('First value')
plt.ylabel('Second value')
plt.xlim(0,90)
plt.ylim(0,90)
plt.xticks(range(0,101,10))
plt.yticks(range(0,101,10))
plt.plot(x,y, color='red', marker='o',ls=':' ,lw=3, ms=10, mfc='green')

plt.title('My first plot')
plt.grid()
plt.xlabel('First value')
plt.ylabel('Second value')
plt.xlim(0,90)
plt.ylim(0,90)
plt.xticks(range(0,101,10))
plt.yticks(range(0,101,10))
plt.plot(x,y,label='2022',color='red')
plt.plot(x,z,label='2023',color='green')
plt.legend()

plt.subplot(1,2,1)
plt.plot(x,y)
plt.subplot(1,2,2)
plt.plot(x,z)

plt.subplot(2,1,1)
plt.plot(x,y)
plt.subplot(2,1,2)
plt.plot(x,z)

plt.figure(figsize=(16,9))
plt.title('My first plot')
plt.grid()
plt.xlabel('First value')
plt.ylabel('Second value')
plt.xlim(0,90)
plt.ylim(0,90)
plt.xticks(range(0,101,10))
plt.yticks(range(0,101,10))
plt.plot(x,y,label='2022',color='red')
plt.plot(x,z,label='2023',color='green')
plt.legend()

plt.figure(figsize=(16,9))
plt.title('My first plot')
plt.grid()
plt.xlabel('First value')
plt.ylabel('Second value')
plt.xlim(0,90)
plt.ylim(0,90)
plt.xticks(range(0,101,10))
plt.yticks(range(0,101,10))
plt.plot(x,y,label='2022',color='red')
plt.plot(x,z,label='2023',color='green')
plt.legend()
plt.savefig('Mygraph.png')



"""Scatter Plot

"""

plt.scatter(x,y)

java=[67,72,46,64,81,40,52,44]
python=[71,75,50,66,85,42,55,45]

plt.scatter(java,python)



studs=[67,89,123,189,105,122]
course=['c','c++','java','Pytthon','PHP','javascript']

plt.title('Total Enrolment')
plt.grid()
plt.xlabel('Courses')
plt.ylabel('Total Studenttss')
plt.barh(course,studs,color='skyblue')

import pandas as pd
df=pd.read_csv('/content/student.csv')

plt.bar(df['name'],df['marks'])

"""Pie Chart

"""

plt.pie(studs,labels=course,autopct='%2.2f%%');

w=[56,67,45,68,65,98,54,35,67,87,55,42]

plt.boxplot(w);



